### ISSUE TITLE
nothing happening

### ISSUE THREAD

**Issue by premod** [ashwitha-n/Whatsapp-bulk-message-sender#1]
hi,
i have installed all the packages, and the latest chrome driver in the same folder, and logged in whatsapp web also,
nothing happening, the msgs not going, 

can u please explain how to use the tool. if u please, it will be a great help

**Comment by ashwitha-n** [comment]
Hi, premod,
You have to have an excel sheet which contains all the phone numbers
without any text i.e., no heading even
Once you execute your code... It opens a Tkinter window, there you are
supposed to enter text or attach the image or document and select the excel
sheet... Then click on submit. Then the chrome driver opens
automatically... for the first time you need to login to WhatsApp web again
in new chrome window. Then it starts sending messages.
I hope this helps you.
If so... Please don't forget to leave a star.

**Comment by premod** [comment]
Dear Ashwitha,
pls go through the video i recorded now. if i corrected it i will be a huge thanks to you
[record-17.29.14[20.06.2020].zip](https://github.com/ashwitha-n/Whatsapp-bulk-message-sender/files/4807834/record-17.29.14.20.06.2020.zip)

**Comment by likhita-1** [comment]
That is an issue with the chrome driver version. Try using the one which is provided in the repo or the one matching the version of your chrome. I am not sure.. even I am a beginner.
By the way, you do not need to install all the packages to run an exe file and You have to use xlsx file only.

**Comment by ashwitha-n** [comment]
That is an issue with the chrome driver version. Try using the one which is provided in the repo or the one matching the version of your chrome. I am not sure.. even I am a beginner.
By the way, you do not need to install all the packages to run an exe file and You have to use xlsx file only.

**Comment by premod** [comment]
not working

**Comment by premod** [comment]
now its working, thank you ashmitha
